services:
  #!postgres:
  postgres:
    image: postgres
    container_name: comercios_postgres
    restart: always
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - ${PG_DB_PORT}:5432
    # volumes:
  #!pgadmin:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: comercios_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
    ports:
      - '5052:80'
    # volumes:
  #!mongo
  mongo:
    image: mongo
    restart: always
    container_name: comercios_mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    # volumes:
  #!mongo-express
  mongo-express:
    image: mongo-express
    restart: always
    container_name: comercios_mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=comercios_mongo
