export enum ExeptionType {
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',
  PERSISTENCE = 'PERSISTENCE',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  DOMAIN_VALIDATION = 'DOMAIN_VALIDATION',
}
